### PR TITLE
Improve DDL consistency with spec table

### PR DESCRIPTION
**Pull request by bradh**

### CODE REVIEW

**Comment by bradh** [comment]
You might want to add the missing columns too - `data_null` and `data_missing`

**Comment by jyutzler** [comment]
@trgn Please take a look at this and correct if needed.

**Comment by thomasneirynck** [comment]
yes, this was not correct. Please merge this (I don't have write access), thx.

**Comment by bradh** [comment]
Lets not do this one. I'll fix the other issues over the weekend.

**Pull request closed without merging**
