### PR TITLE
Promoting SRS use

### PR DESCRIPTION
**Pull request by jyutzler**
addressed #16

### CODE REVIEW

**Comment by jyutzler** [comment]
I'd say that LIDAR data isn't elevation data so this extension doesn't solve your problem.
For now you can either produce an elevation product from the LIDAR or you can make your own extension (preferably informed by this one) for holding the LIDAR data.

There has been talk of an extension for general-purpose coverages but to this point it hasn't bubbled up as a priority. There was a strong urge to solve the elevation problem as quickly as possible.

**Comment by bradh** [comment]
Ignore the LIDAR part - the source of elevation data isn't relevant here. If I give you elevation data in GeoTIFF format, referenced to EPSG:2193 (real world example: https://data.linz.govt.nz/layer/1768-nz-8m-digital-elevation-model-2012/) , that is going to be hard to convert to GeoPackage.

The issue is that you're restricting to 3D SRS, and there is not always a 3D SRS equivalent for the 2D SRS + elevation case.

**Comment by jyutzler** [comment]
Because I mismanaged my repo (making a change to jyutzler/.../master instead of a branch), this comment got put in the wrong place.
https://github.com/opengeospatial/geopackage-elevation/pull/18#issuecomment-159172888

**Comment by jyutzler** [comment]
This was supposed to have been merged. I must have missed it before.

**Comment by bradh** [comment]
I though there was no concensus and we were still discussing it...

**Pull request merged**
